-----BEGIN EC PRIVATE KEY-----
MIGkAgEBBDBvxi8aXV5jU+MwRkpoelgFZ/LzzCrPlQR0OSEKgpeSRRCSetBj2dxk
h6CiLrlyjyegBwYFK4EEACKhZANiAAS3M7ReALo8ax9f2JUY5nCvSC2tvzTOJ54o
Oo7YiVMFHgnPllBCsATv3dHx/c+XBzISk8aoQgi3VU3YEuzEFEBXNnz6lAQKrj7f
dbOIXzw9J9Jnggi/eekatlrd9y2NrQc=
-----END EC PRIVATE KEY-----
